{% set version = "0.12" %}
package:
    name: seamless-cli-bin
    version: {{ version }}

build:
  number: 2

requirements:
  build:
    - python
  run:
    - seamless-framework
about:
  summary: This is a re-implementation of seamless-cli, invoking the underlying tools directly.
