{% set version = "0.13" %}
package:
    name: seamless-cli-bin
    version: {{ version }}

build:
  number: 1

requirements:
  build:
    - python>=3.10
  run:
    - seamless-framework=0.13
about:
  summary: This is a re-implementation of seamless-cli, invoking the underlying tools directly.
