[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hashserver"
version = "1.1.0"
description = "Simple FastAPI-based hash server"
readme = "README.md"
license = "MIT"
authors = [{name = "Sjoerd de Vries"}]
requires-python = ">=3.10"
dependencies = [    
    "fastapi",
    "uvicorn[standard]",
    "typing-extensions",
    "zstandard",
]
keywords = ["seamless", "content-addressed", "file server", "HTTP"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries",
]

[project.urls]
Homepage = "https://github.com/sjdv1982/hashserver"
Repository = "https://github.com/sjdv1982/hashserver"

[project.optional-dependencies]
dev = []

[tool.setuptools]
py-modules = ["hashserver", "hash_file_response", "compression_utils"]

[project.scripts]
hashserver = "hashserver:main"

