#!/bin/bash
export SEAMLESS_COMMUNION_ID=Peer1
export SEAMLESS_COMMUNION_IP=""
export SEAMLESS_COMMUNION_PORT=""
export SEAMLESS_COMMUNION_OUTGOING_IP=0.0.0.0
export SEAMLESS_COMMUNION_OUTGOING_PORT=8601
#export SEAMLESS_COMMUNION_INCOMING=localhost:8602,localhost:8603
#export SEAMLESS_COMMUNION_INCOMING=localhost:8602
python3 communion-peer1.py 