#!/bin/bash
export SEAMLESS_COMMUNION_ID=Peer2
export SEAMLESS_COMMUNION_IP=$SEAMLESS_DOCKER_HOST_IP
export SEAMLESS_COMMUNION_PORT=8601
#export SEAMLESS_COMMUNION_OUTGOING_PORT=8602
#export SEAMLESS_COMMUNION_INCOMING=$SEAMLESS_DOCKER_HOST_IP:8601
python3 communion-peer2.py
