ctx.uniforms = cell("json")
ctx.uniforms.connect(ctx.glprogram.uniforms)
ctx.params_gen_uniforms = cell(("cson", "seamless", "reactor_params"))
link(ctx.params_gen_uniforms, ".", "params_gen_uniforms.cson")
if not ctx.params_gen_uniforms.value: ### kludge: to be fixed in seamless 0.2
    ctx.params_gen_uniforms.set("{}")
ctx.gen_uniforms = reactor(ctx.params_gen_uniforms)
link(ctx.gen_uniforms.code_start.cell(), ".", "cell-gen-uniforms-start.py")
link(ctx.gen_uniforms.code_update.cell(), ".", "cell-gen-uniforms-update.py")
ctx.gen_uniforms.code_stop.cell().set("")
