name: seamless-framework
channels:
  - conda-forge
  - rpbs
dependencies:
  - python
  - pip
  - rpbs::seamless-framework==0.11
  - rpbs::silk>=0.1.10
  - conda
  - pip:
    - websockets
    - cson
    - speg
    - aiohttp_cors
