name: seamless-mini
channels:
  - conda-forge
  - rpbs
dependencies:
  - python
  - pip
  - rpbs::seamless-framework==0.12
  - rpbs::silk>=0.1.10
  - conda
  - jinja2
  - traitlets
  - datrie  # required to build some pip packages
  - ipython<=8.16.*
  - ipykernel

  - cffi
  - jinja2
  - traitlets
  - ipywidgets
  - debugpy
  - openmp
  - wurlitzer
  - cython
  - commentjson
  - expandvars
  - pip:
    - websockets
    - cson
    - speg
    - aiohttp_cors
    - makefun