name: seamless-mini
channels:
  - conda-forge
  - rpbs
dependencies:
  - python
  - pip
  - rpbs::seamless-framework==0.12
  - rpbs::silk>=0.1.11
  - rpbs::seamless-cli-complement
  - rpbs::seamless-cli-bin
  - conda
  - aiohttp-cors
  - jinja2
  - traitlets
  - datrie  # required to build some pip packages
  - ipython<=8.16.*
  - ipykernel

  - cffi
  - jinja2
  - traitlets
  - ipywidgets
  - debugpy
  - openmp
  - wurlitzer
  - cython
  - commentjson
  - expandvars
  - pip:
    - websockets
    - cson
    - speg    
    - makefun
variables:
  SEAMLESS_CONDA_ENVIRONMENT: 1
  SEAMLESS_DEFAULT_ASSISTANT_IP: 127.0.0.1
  SEAMLESS_DEFAULT_ASSISTANT_PORT: 5533
  SEAMLESS_DATABASE_IP: 127.0.0.1
  SEAMLESS_DATABASE_PORT: 5522
  SEAMLESS_READ_BUFFER_SERVERS: http://127.0.0.1:5577
  SEAMLESS_WRITE_BUFFER_SERVER: http://127.0.0.1:5577
  SEAMLESS_DEBUGGING_DIRECTORY: /tmp/seamless-debug
