name: seamless-framework
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - rpbs::seamless-framework
  - conda=4.12
  - mamba
  - pip:
    - nglview
    - snakemake
    - cson==0.8
    - speg==0.3
    - websockets==10.3
    - aiohttp_cors==0.7.*
    - jupyter-console==6.4.*
    - docker==6.0.*
    - itables==1.3.*
    - debugpy==1.6.*
    - tornado==6.2.*
    - orjson

variables:
    RPY2_CFFI_MODE: ABI
