name: seamless-micro
channels:
  - conda-forge
  - rpbs
dependencies:
  - python
  - pip
  - rpbs::seamless-framework==0.12
  - rpbs::silk>=0.1.11
  - conda
  - pip:
    - websockets
    - cson
    - speg
    - aiohttp_cors
variables:
  SEAMLESS_CONDA_ENVIRONMENT: 1