name: seamless-framework
channels:
  - conda-forge
  - rpbs
dependencies:
  - python
  - pip
  - rpbs::seamless-framework==0.11
  - rpbs::silk>=0.1.10
  - conda
  - ipython
  - ipykernel

  - cffi
  - jinja2
  - traitlets
  - ipywidgets
  - debugpy
  - openmp
  - wurlitzer
  - cython
  - commentjson
  - expandvars
  - pip:
    - websockets
    - cson
    - speg
    - aiohttp_cors
    - makefun

variables:
    RPY2_CFFI_MODE: ABI
