name: seamless-exact
channels:
  - conda-forge
  - rpbs
dependencies:
  # keep this in sync with seamless-tools/docker/seamless-deps-environment.yml
  - python=3.10.*
  - pip=23.0.*
  - numpy=1.24.*
  - rpbs::seamless-framework==0.12
  - rpbs::silk==0.1.11
  - rpbs::seamless-cli-complement
  - rpbs::seamless-cli-bin
  - rpbs::seamless-scripts
  - bashlex=0.18
  - conda=23.1.*
  - aiohttp-cors==0.7.*
  - ruamel.yaml=0.17.*
  - orjson=3.8.*
  - psutil=5.9.*
  - jinja2=3.1.*
  - traitlets=5.9.*
  - datrie  # required to build some pip packages
  - jsonschema=4.18.*
  - ipython=8.15.*
  - ipykernel=6.21.*

  - cffi=1.15.*
  - ipywidgets=8.0.*  
  - debugpy=1.6.*
  - openmp=8.0.*
  - requests=2.31.*
  - wurlitzer=3.0.*
  - psutil=5.9.*
  - cython=0.29.*
  - commentjson
  - expandvars
  - notebook=6.5.*
  - jupyterhub=3.1.*
  - jupyterlab=3.6.*
  - scipy
  - pandas
  - r-base=4.2.*
  - scikit-learn=1.2.*
  - r-cairo=1.6_0.*
  - rpy2==3.5.*
  - sympy
  - pip:
    - websockets==10.3.*
    - docker==7.0.*
    - makefun
    - nglview
    - matplotlib 
    - snakemake==7.18.*
    - jupyter-console==6.6.*
    - itables==1.4.*
variables:
  SEAMLESS_CONDA_ENVIRONMENT: 1
  SEAMLESS_DEFAULT_ASSISTANT_IP: 127.0.0.1
  SEAMLESS_DEFAULT_ASSISTANT_PORT: 5533
  SEAMLESS_DATABASE_IP: 127.0.0.1
  SEAMLESS_DATABASE_PORT: 5522
  SEAMLESS_READ_BUFFER_SERVERS: http://127.0.0.1:5577
  SEAMLESS_WRITE_BUFFER_SERVER: http://127.0.0.1:5577
  SEAMLESS_DEBUGGING_DIRECTORY: /tmp/seamless-debug
