name: seamless-framework
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - rpbs::seamless-framework==0.11
  - rpbs::silk>=0.1.10
  - conda
  - ipython
  - ipykernel
  - aiofiles
  - cffi
  - traitlets
  - ipywidgets
  - debugpy
  - openmp
  - wurlitzer
  - cython
  - commentjson
  - expandvars
  - notebook
  - jupyterhub
  - jupyterlab
  - scipy
  - pandas
  - r-base
  - scikit-learn
  - r-cairo
  - rpy2
  - sympy
  - pip:
    - websockets
    - cson
    - speg
    - aiohttp_cors
    - docker
    - rpbs::seamless-cli
    - makefun
    - nglview
    - matplotlib 
    - snakemake
    - jupyter-console
    - itables

variables:
    RPY2_CFFI_MODE: ABI
