name: seamless-framework
channels:
  - conda-forge
  - rpbs
dependencies:
  - python
  - pip
  - numpy
  - rpbs::seamless-framework==0.13.*
  - rpbs::silk>=0.1.11
  - rpbs::seamless-cli-complement
  - rpbs::seamless-cli-bin==0.13.*
  - bashlex
  - conda
  - aiohttp-cors
  - ruamel.yaml
  - orjson
  - psutil
  - jinja2
  - traitlets
  - datrie # required to build some pip packages
  - jsonschema=4.18.*
  - ipython<=8.16
  - ipykernel

  - cffi
  - ipywidgets
  - debugpy
  - openmp
  - requests=2.31.*
  - wurlitzer
  - psutil
  - cython
  - commentjson
  - expandvars
  - notebook
  - jupyterhub
  - jupyterlab
  - scipy
  - pandas
  - r-base
  - scikit-learn
  - r-cairo
  - rpy2
  - sympy
  - pip:
      - websockets
      - docker
      - makefun
      - nglview
      - matplotlib
      - snakemake==7.18.*
      - jupyter-console
      - itables==1.4.*
variables:
  SEAMLESS_CONDA_ENVIRONMENT: 1
  SEAMLESS_DEFAULT_ASSISTANT_IP: 127.0.0.1
  SEAMLESS_DEFAULT_ASSISTANT_PORT: 5533
  SEAMLESS_DATABASE_IP: 127.0.0.1
  SEAMLESS_DATABASE_PORT: 5522
  SEAMLESS_READ_BUFFER_SERVERS: http://127.0.0.1:5577
  SEAMLESS_WRITE_BUFFER_SERVER: http://127.0.0.1:5577
  SEAMLESS_DEBUGGING_DIRECTORY: /tmp/seamless-debug
