name: seamless-framework
channels:
  - conda-forge
  - rpbs
dependencies:
  - python
  - pip
  - numpy
  - rpbs::seamless-framework==0.12
  - rpbs::silk>=0.1.10
  - rpbs::seamless-cli
  - bashlex
  - conda
  - ruamel.yaml
  - orjson
  - psutil
  - jinja2
  - traitlets
  - datrie  # required to build some pip packages
  - jsonschema=4.17.*
  - ipython<=8.16.*
  - ipykernel

  - cffi
  - ipywidgets
  - debugpy
  - openmp
  - requests<2.29.*
  - wurlitzer
  - psutil
  - cython
  - commentjson
  - expandvars
  - notebook
  - jupyterhub
  - jupyterlab
  - scipy
  - pandas
  - r-base
  - scikit-learn
  - r-cairo
  - rpy2
  - sympy
  - pip:
    - websockets
    - cson
    - speg
    - aiohttp_cors
    - docker
    - makefun
    - nglview
    - matplotlib 
    - snakemake==7.18.*
    - jupyter-console
    - itables
variables:
    RPY2_CFFI_MODE: ABI
