FROM jupyter/scipy-notebook:latest
LABEL author="Sjoerd de Vries <sjoerd.de-vries@inserm.fr>"
LABEL version="0.2"
USER root
RUN pip install -r requirements.txt
RUN pip install seamless-framework==0.2
