FROM jupyter/scipy-notebook:latest
LABEL author="Sjoerd de Vries <sjoerd.de-vries@inserm.fr>"
LABEL version="0.2"
RUN pip install cson websockets aiohttp aiohttp_cors wurlitzer nest_asyncio redis docker jsonschema==3.0.0a3 seamless-framework 
