from seamless.highlevel import Context, Cell
ctx = Context()

ctx.v = "test"
ctx.v_schema = Cell()
ctx.v_schema.celltype = "plain"
ctx.mount("/tmp/mount-test")
ctx.link(ctx.v.schema, ctx.v_schema)
ctx.translate()
ctx.v_schema.set({'type': 'integer'})
ctx.equilibrate()
print(ctx.v.schema)
print("*" * 50)
print(ctx.v.exception)
print("*" * 50)
ctx.v.schema.set({})
print(ctx.v.schema)
print(ctx.v_schema.value)
print(ctx.v.example.set(1.2))
ctx.equilibrate()
print(ctx.v.value)
print(ctx.v.data)
print("buffered:", ctx.v.buffered)
print(ctx.v_schema.value)
print(ctx.v_schema.set({"type": "string"}))
ctx.equilibrate()
print(ctx.v_schema.value)
print(ctx.v.schema)
