name: seamless-minimal
# keep this in sync with seamless/conda/seamless-exact-environment.yml
# and seamless-tools/docker/seamless-deps-environment.yml
channels:
  - rpbs
  - conda-forge
dependencies:
  - python=3.10.*
  - conda=23.1.*
  - silk>=0.1.10
  - pip=23.0.*
  - numpy=1.24.*
  - ruamel.yaml=0.17.*
  - orjson=3.8.*
  - datrie
  - jsonschema=4.17.*
  - requests=2.28.*
  - wurlitzer=3.0.*
  - psutil=5.9.*
  - cffi=1.15.*
  - cython=0.29.*
  - scipy
  - pandas
  - r-base=4.2.*
  - scikit-learn=1.2.*
  - r-cairo=1.6_0.*
  - rpy2==3.5.*
  - sympy
  - pip:
    - makefun
    - matplotlib  
    - cson==0.8.*
    - speg


