name: seamless-minimal
channels:
  - rpbs
  - conda-forge
dependencies:
  - python=3.8.8
  - conda=4.10.*
  - mamba=0.12.*
  - silk>=0.1.8
  - pip
  - numpy==1.20.*
  - ruamel.yaml=0.16.*
  - speg=0.3.*
  - jsonschema=3.2.*
  - requests=2.22.*
  - wurlitzer=2.0.*
  - yarl=1.7.*
  - psutil=5.8.*
  - pandas=1.2.*
  - cffi=1.14.*  
  - pandas=1.2.*
  - rpy2=3.4.*
  - cython=0.29.*
  - r-base=4.0.*
  - r-cairo=1.5_12.*
  - scipy=1.6.*
  - blas=1.1=openblas
  - scikit-learn=0.24.*
  - sympy=1.8.*
  - matplotlib
  - pip:
    - cson==0.8.*
    - orjson


