#!/bin/bash

kernels=$(ls -1 /home/jovyan/.local/share/jupyter/runtime/kernel-*.json 2> /dev/null)
nkernels=$(echo "$kernels" | awk 'BEGIN{count=0} NF{count += 1} END{print count}')

if [ $nkernels -eq 0 ]; then
    echo 'No running Jupyter kernels found' > /dev/stderr
    exit 1
fi
if [ $nkernels -gt 1 ]; then
    echo '*****************************************************' > /dev/stderr
    echo '* Multiple running Jupyter kernels found' > /dev/stderr
    echo '*****************************************************' > /dev/stderr
    echo 'You will need to specify a kernel using: "--existing KERNEL_CONNECTION_FILE.json"' > /dev/stderr
    echo '' > /dev/stderr
    echo '1. If you want to connect to a Seamless transformer debug shell:' > /dev/stderr
    echo 'simply type again Transformer.debug.shell() to get the kernel connection file.' > /dev/stderr
    echo '' > /dev/stderr
    echo '2. If you want to connect to a kernel that was started with' > /dev/stderr
    echo ' Jupyter notebook, Jupyterlab or Jupyter console, execute there the following code:' > /dev/stderr
    echo '' > /dev/stderr
    echo 'from ipykernel.zmqshell import get_connection_file; get_connection_file()'> /dev/stderr
    echo '' > /dev/stderr
    exit 1
fi

jupyter console --existing