#!/usr/bin/env python3

import sys
assert len(sys.argv) == 2 #syntax: seamless file.seamless

cmd = """import seamless
from seamless import context, cell, transformer
from seamless.lib import link, edit, display
from seamless.gui import shell
ctx = seamless.fromfile('%s')""" % sys.argv[1]
sys.argv = [sys.argv[0], "-c", cmd, "-i"]

from IPython import start_ipython
sys.exit(start_ipython())
