#!/bin/bash

set -u -e

# - Current directory is mounted to /cwd, and the command is executed there
# - Seamless has access to the Docker daemon, so it can launch its own Docker
#    containers via the Docker transformer. This works only under Linux.
#    NOTE: THIS IS A BIG SECURITY HOLE, IT CAN GIVE ROOT ACCESS TO YOUR SYSTEM
# /tmp is also mounted, this is needed by Docker transformers (as they run on the host)

seamlessdir=$SEAMLESSDIR

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

docker run --rm \
  $gdbflags \
  -v $seamlessdir:/seamless \
  -e "PYTHONPATH=/seamless" \
  --network=host \
  -v `pwd`:/cwd \
  -v /tmp:/tmp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $(getent group docker | cut -d: -f3) \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  seamless-devel start.sh python3 -u /seamless/scripts/serve-graph.py $*
