#!/bin/bash

set -u -e

# - Current directory is mounted to /cwd, and the command is executed there

seamlessdir=$SEAMLESSDIR
zipfile_dir=`python3 -c 'import os,sys;print(os.path.abspath(os.path.dirname(sys.argv[1])))' $1`
zipfile_name=${1##*/}

cd ${zipfile_dir}

docker run --rm \
  -v $seamlessdir:/seamless \
  -e "PYTHONPATH=/seamless" \
  --network=host \
  -v `pwd`:/cwd \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  seamless-devel start.sh python3 /home/jovyan/seamless-scripts/add-zip.py ${zipfile_name}
