#!/bin/bash

# runs a transformation in the seamless-minimal Docker image
# $1: the environment dir
# $2: the transformation checksum

set -u -e

CONDA_ENV_DIR=$1
tf_checksum=$2
shift 1

docker run \
  --rm \
  -it \
  -u `id -u` \
  -e CONDA_ENV_DIR=$CONDA_ENV_DIR \
  -v $CONDA_ENV_DIR:$CONDA_ENV_DIR \
  -e tf_checksum=$tf_checksum \
  rpbs/seamless-minimal \
  bash -i -c '''
  echo "conda activate $CONDA_ENV_DIR" >> /.bashrc
  bash -c -i "python /seamless-scripts/run-transformation.py $tf_checksum $*"
  ''' $*