#!/bin/bash

# Creates a new Seamless project in the current directory

set -e

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`
source $currdir/seamless-fill-environment-variables

set -u -e

docker run --rm \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_NAME \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL \
  -e DOCKER_IMAGE=$SEAMLESS_DOCKER_IMAGE \
  -e HOSTCWD=`pwd` \
  -e SHARESERVER_ADDRESS=$SEAMLESS_SHARESERVER_ADDRESS \
  -e SEAMLESS_DOCKER_HOST_IP=$SEAMLESS_DOCKER_HOST_IP \
  -e SEAMLESS_DATABASE_IP=$SEAMLESS_DATABASE_IP \
  -e SEAMLESS_DATABASE_PORT=$SEAMLESS_DATABASE_PORT \
  -v `pwd`:/cwd \
  --workdir /cwd \
  -u `id -u`:`id -g` \
  --group-add users \
  $SEAMLESS_DOCKER_IMAGE start.sh python3 -u /home/jovyan/seamless-scripts/new-project.py $*
