#!/bin/bash

set -e

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`
source $currdir/seamless-fill-environment-variables

set -u -e

# - Current directory is mounted to /cwd, and the command is executed there

zipfile_dir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $1`
zipfile_name=${1##*/}

cd ${zipfile_dir}

docker run --rm \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL \
  -v `pwd`:/cwd \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  -e SEAMLESS_DATABASE_IP=$SEAMLESS_DATABASE_IP \
  -e SEAMLESS_DATABASE_PORT=$SEAMLESS_DATABASE_PORT \
  $SEAMLESS_DOCKER_IMAGE start.sh python3 /home/jovyan/seamless-scripts/add-zip.py ${zipfile_name}
