#!/bin/bash
set -u -e

[ ! -d ~/.seamless/redis ] && mkdir -p ~/.seamless/redis

docker run \
  --rm \
  -d \
  -p 6379:6379 \
  --name seamless-redis-container \
  -v ~/.seamless/redis:/data \
  -u `id -u`:`id -g` \
  redis redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy volatile-ttl
