#!/bin/bash
set -e

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`
source $currdir/seamless-fill-environment-variables

set -u -e

docker run --rm \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL \
  $SEAMLESS_DOCKER_RUN_PARAMS_X_NETWORK \
  -e SEAMLESS_DOCKER_HOST_IP=$SEAMLESS_DOCKER_HOST_IP \
  -v `pwd`:/cwd \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  $SEAMLESS_DOCKER_IMAGE start.sh python3 -u /home/jovyan/seamless-scripts/http-put.py $*
