#!/bin/bash

database_config=$1
: ${database_config:=/home/jovyan/seamless-tools/default-config.yaml}

set -u -e

[ ! -d ~/.seamless/database ] && mkdir -p ~/.seamless/database
[ ! -d ~/.seamless/redis ] && mkdir -p ~/.seamless/redis

seamlessdir=`python3 -c 'import seamless,os;print(os.path.dirname(seamless.__file__))'`/../


docker run \
  --rm \
  -d \
  -p 6379:6379 \
  --name seamless-redis-container \
  -v ~/.seamless/redis:/data \
  -u `id -u`:`id -g` \
  redis redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy volatile-ttl


echo 'Running Seamless database adapter with' $database_config
docker run \
  --rm \
  -p 5522:5522 \
  --name seamless-database-container \
  -v ~/.seamless/database:/data \
  -v $seamlessdir:/seamless \
  -e "PYTHONPATH=/seamless" \
  -u jovyan \
  -v /tmp:/tmp \
  -v `pwd`:/cwd \
  --workdir /cwd \
  seamless-devel \
  python3 -u /home/jovyan/seamless-tools/database.py \
  $database_config
