#!/bin/bash

set -u -e

# Version of the seamless command that creates an interactive bash shell inside the seamless-devel image

# NOTE: GIVES ACCESS TO THE DOCKER DAEMON. THIS IS A BIG SECURITY HOLE, IT CAN GIVE ROOT ACCESS TO YOUR SYSTEM

seamlessdir=$SEAMLESSDIR
HOSTCWD=`pwd`

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

if [[ ! -v SEAMLESS_DEBUGGING_DIRECTORY ]]; then 
  SEAMLESS_DEBUGGING_DIRECTORY=/tmp/seamless-debug
  mkdir -p ${SEAMLESS_DEBUGGING_DIRECTORY}
fi

containerID=$(docker run --rm \
   $gdbflags \
   -e "DOCKER_IMAGE=rpbs/seamless" \
   -e "SEAMLESS_DEBUGGING_DIRECTORY=${SEAMLESS_DEBUGGING_DIRECTORY}" \
   --network=host \
   -d \
  -v $seamlessdir:/seamless \
  -e "PYTHONPATH=/seamless" \
  -e HOSTCWD=$HOSTCWD \
  -v $HOSTCWD:/cwd \
  -v /tmp:/tmp \
  -v ${SEAMLESS_DEBUGGING_DIRECTORY}:${SEAMLESS_DEBUGGING_DIRECTORY} \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $(getent group docker | cut -d: -f3) \
  --workdir /cwd \
  -it \
  -u `id -u` \
  --group-add users \
  $* \
  seamless-devel start.sh)
echo $containerID | docker exec -i $containerID /bin/bash -c 'cat > /home/jovyan/DOCKER_CONTAINER'
docker attach $containerID
