#!/bin/bash

set -e

database_dir=$1
: ${database_dir:=~/.seamless/database}

set -u -e

[ ! -d $database_dir ] && mkdir -p $database_dir

database_port=$2
: ${database_port:=5522}

database_host=$3
: ${database_host:='0.0.0.0'}

seamlessdir=$SEAMLESSDIR

echo "Starting container seamless-database-container"
docker run \
  -d \
  -p $database_port:$database_port \
  --name seamless-database-container \
  -v $database_dir:/data \
  -e "SEAMLESS_DATABASE_DIR=/data" \
  -e "SEAMLESS_DATABASE_PORT=$database_port" \
  -e "SEAMLESS_DATABASE_HOST=$database_host" \
    -u `id -u` \
  --group-add users \
  -v /tmp:/tmp \
  -v `pwd`:/cwd \
  --workdir /cwd \
  rpbs/seamless start.sh python3 -u /home/jovyan/seamless-tools/database.py
