#!/bin/bash

set -u -e

# Version of the seamless command meant for hacking on Seamless
# Python tracebacks now show the correct file, clickable in VS Code
# creates an interactive bash shell inside the seamless-devel image

# NOTE: GIVES ACCESS TO THE DOCKER DAEMON. THIS IS A BIG SECURITY HOLE, IT CAN GIVE ROOT ACCESS TO YOUR SYSTEM

seamlessdir=`python3 -c 'import seamless,os;print(os.path.dirname(seamless.__file__))'`/../

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

docker run --rm \
  $gdbflags \
  -v $seamlessdir:$seamlessdir \
  -e "PYTHONPATH="$seamlessdir \
  --network=host \
  -v `pwd`:/cwd \
  -v /tmp:/tmp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $(getent group docker | cut -d: -f3) \
  --workdir /cwd \
  -it \
  -u `id -u` \
  --group-add users \
  seamless-devel start.sh
