#!/bin/bash

set -u -e

# add --ip='0.0.0.0' to allow connections from outside

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

if [[ ! -v SEAMLESS_DEBUGGING_DIRECTORY ]]; then 
  SEAMLESS_DEBUGGING_DIRECTORY=/tmp/seamless-debug
  mkdir -p ${SEAMLESS_DEBUGGING_DIRECTORY}
fi

docker run --rm \
  $gdbflags \
  -e DOCKER_IMAGE=rpbs/seamless \
  -e "SEAMLESS_DEBUGGING_DIRECTORY=${SEAMLESS_DEBUGGING_DIRECTORY}" \
  -v /tmp:/tmp \
  -v ${SEAMLESS_DEBUGGING_DIRECTORY}:${SEAMLESS_DEBUGGING_DIRECTORY} \
  -v `pwd`:/home/jovyan/cwd \
  --network=host \
  --hostname localhost \
  --workdir /home/jovyan \
  -u `id -u` \
  --group-add users \
  rpbs/seamless start-notebook.sh \
  --NotebookApp.token='' --NotebookApp.password='' \
  $*
