#!/bin/bash
set -u -e

# Creates a new Seamless project in the current directory

docker run --rm \
  -e DOCKER_IMAGE=rpbs/seamless \
  -v `pwd`:/cwd \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  rpbs/seamless start.sh python3 -u /home/jovyan/seamless-scripts/new-project.py $*
