#!/bin/bash

set -u -e

# add --ip='0.0.0.0' to allow connections from outside

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

docker run --rm \
  $gdbflags \
  -v /tmp:/tmp \
  -v `pwd`:/home/jovyan/cwd \
  --network=host \
  --hostname localhost \
  --workdir /home/jovyan \
  -u `id -u` \
  --group-add users \
  rpbs/seamless start-notebook.sh \
  --NotebookApp.token='' --NotebookApp.password='' \
  $*
