#!/bin/bash

set -u -e

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###
HOSTCWD=`pwd`


containerID=$(docker run --rm \
  $gdbflags \
  -e DOCKER_IMAGE=rpbs/seamless \
  --network=host \
  -d \
  -e HOSTCWD=$HOSTCWD \
  -v $HOSTCWD:/cwd \
  --workdir /cwd \
  -it \
  -u `id -u` \
  --group-add users \
  $* \
  rpbs/seamless start.sh)

echo $containerID | docker exec -i $containerID /bin/bash -c 'cat > /home/jovyan/DOCKER_CONTAINER'
docker attach $containerID
