#!/bin/bash
set -u -e

# Runs a Jupyter console terminal inside an existing Seamless Docker image

containers=$(docker ps --filter ancestor=rpbs/seamless)
ncontainers=$(echo "$containers" | wc -l)
if [ $ncontainers -eq 1 ]; then
    echo 'No running Seamless Docker containers found' 1>&2
    exit 1
fi
if [ $ncontainers -gt 2 ]; then
    echo '*****************************************************' 1>&2
    echo '* Multiple Seamless Docker containers found' 1>&2
    echo '*****************************************************' 1>&2
    echo 'Do "docker ps --filter ancestor=rpbs/seamless", and look at the last field.' 1>&2
    echo 'It will be something like "jolly_einstein". Select the one you want.' 1>&2
    echo 'Then, do "docker exec -it --user jovyan jolly_einstein bash"' 1>&2
    echo 'Finally, do "~/seamless-scripts/jupyter-console-existing"' 1>&2
    exit 1
fi

container=$(echo "$containers" | tail -1 | awk '{print $NF}')
docker exec -it --user jovyan $container bash -c "~/seamless-scripts/jupyter-console-existing"