#!/bin/bash
set -u -e

# Loads a Seamless project in IPython inside the Seamless Docker image
# - Current directory is mounted to /cwd, and the command is executed there
# - /tmp is mounted as well

# NOTE: GIVES ACCESS TO THE DOCKER DAEMON. THIS IS A BIG SECURITY HOLE, IT CAN GIVE ROOT ACCESS TO YOUR SYSTEM

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

if [ ! -f load-project.py ]; then
  echo 'Current directory is not a Seamless project'
  exit 1
fi

docker run --rm -it \
  $gdbflags \
  --network=host \
  -v `pwd`:/cwd \
  -v /tmp:/tmp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $(getent group docker | cut -d: -f3) \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  rpbs/seamless start.sh ipython3 -i -c '%run -i load-project.py
await load()'
