#!/bin/bash

set -u -e

seamlessdir=$SEAMLESSDIR

set +u -e

get_docker_params='''
import sys, os
import ruamel.yaml
yaml = ruamel.yaml.YAML(typ="safe")
config = yaml.load(open(sys.argv[1]))
assert isinstance(config, dict)
port = int(config.get("port", 5522))
result="-p {}:{}".format(port, port)
assert "stores" in config
for store in config["stores"]:
    assert isinstance(store, dict)    
    path = store["path"]
    external_path = store.get("external_path")
    if external_path is None:
        external_path = path
    external_path = os.path.realpath(os.path.expanduser(external_path))
    if not os.path.exists(external_path):
        os.mkdir(external_path)
    result += " -v {}:{}".format(external_path, path)
    if store.get("readonly"):
        result += ":ro"
    result += " "
print(result)
'''

if [ -z "$1" ]; then
  database_config=$seamlessdir/tools/default-database.yaml  
else
  database_config=$(python -c "import sys, os; print(os.path.realpath(sys.argv[1]))" $1)
fi
docker_params=$(echo "$get_docker_params" | python /dev/stdin $database_config)

set -u -e

echo "Starting container seamless-database-container"

docker run \
  -d \
  --name seamless-database-container \
  -v $database_config:/database-config.yaml:ro \
  -v $seamlessdir:/seamless \
  $docker_params \
  -u `id -u` \
  --group-add users \
  seamless-devel start.sh python3 -u /seamless/tools/database.py /database-config.yaml
