#!/bin/bash

set -u -e

# - Seamless has access to the Docker daemon, so it can launch its own Docker
#    containers via the Docker transformer. This works only under Linux.
#    NOTE: THIS IS A BIG SECURITY HOLE, IT CAN GIVE ROOT ACCESS TO YOUR SYSTEM

# add --ip='0.0.0.0' to allow connections from outside

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

docker run --rm \
  $gdbflags \
  --network=host \
  -v `pwd`:/home/jovyan/cwd \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $(getent group docker | cut -d: -f3) \
  -v /tmp:/tmp \
  --hostname localhost \
  --workdir /home/jovyan \
  -u `id -u` \
  --group-add users \
  rpbs/seamless start-notebook.sh  \
  --NotebookApp.token='' --NotebookApp.password='' \
  $*
