#!/bin/bash

database_config=$1
: ${database_config:=/home/jovyan/seamless-tools/default-config.yaml}

set -u -e

[ ! -d ~/.seamless/database ] && mkdir -p ~/.seamless/database

echo "Starting container seamless-database-container"
echo 'Running Seamless database adapter with' $database_config
docker run \
  -d \
  -p 5522:5522 \
  --name seamless-database-container \
  -v ~/.seamless/database:/data \
  -u `id -u` \
  --group-add users \
  rpbs/seamless start.sh python3 -u /home/jovyan/seamless-tools/database.py \
  $database_config
