#!/bin/bash
set -u -e

[ ! -d ~/.seamless/redis ] && mkdir -p ~/.seamless/redis

docker run \
  --rm \
  -p 6379:6379 \
  --name redis-container \
  -v ~/.seamless/redis:/data \
  -u jovyan \
  redis redis-server --appendonly yes