#!/bin/bash

# version of jupyter-seamless-devel with full manual Jupyter configuration
seamlessdir=$SEAMLESSDIR

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###


docker run --rm \
  $gdbflags \
  -e DOCKER_IMAGE=rpbs/seamless \
  -v `pwd`:/home/jovyan/cwd -v $seamlessdir:/seamless \
  -e "PYTHONPATH=/seamless" \
  --network=host \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $(getent group docker | cut -d: -f3) \
  -v /tmp:/tmp \
  --hostname localhost \
  --workdir /home/jovyan \
  -u `id -u` \
  --group-add users \
  seamless-devel start-notebook.sh  \
  $*
