#!/bin/bash
set -u -e

# Loads a Seamless project in IPython inside the Seamless Docker image
# - Current directory is mounted to /cwd, and the command is executed there
# - /tmp is mounted as well

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

if [ ! -f load-project.py ]; then
  echo 'Current directory is not a Seamless project'
  exit 1
fi

if [[ ! -v SEAMLESS_DEBUGGING_DIRECTORY ]]; then 
  SEAMLESS_DEBUGGING_DIRECTORY=/tmp/seamless-debug
  mkdir -p ${SEAMLESS_DEBUGGING_DIRECTORY}
fi

docker run --rm -it \
  $gdbflags \
  -e DOCKER_IMAGE=rpbs/seamless \
  -e "SEAMLESS_DEBUGGING_DIRECTORY=${SEAMLESS_DEBUGGING_DIRECTORY}" \
  --network=host \
  -v `pwd`:/cwd \
  -v /tmp:/tmp \
  -v ${SEAMLESS_DEBUGGING_DIRECTORY}:${SEAMLESS_DEBUGGING_DIRECTORY} \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  rpbs/seamless start.sh ipython3 -i -c '%run -i load-project.py
await load()'
