#!/bin/bash
set -u -e

host_ip=$(docker network inspect bridge \
  | python3 -c '''
import json, sys
bridge = json.load(sys.stdin)
print(bridge[0]["IPAM"]["Config"][0]["Gateway"])
''')

# - Current directory is mounted to /cwd, and the command is executed there
# - Seamless has access to the Docker daemon, so it can launch its own Docker
#    containers via the Docker transformer. This works only under Linux.
#    NOTE: THIS IS A BIG SECURITY HOLE, IT CAN GIVE ROOT ACCESS TO YOUR SYSTEM
# /tmp is also mounted, this is needed by Docker transformers (as they run on the host)

docker run --rm \
  -e DOCKER_IMAGE=rpbs/seamless \
  --network=host \
  -v `pwd`:/cwd \
  -v /tmp:/tmp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $(getent group docker | cut -d: -f3) \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  rpbs/seamless start.sh ipython3 -i /home/jovyan/seamless-scripts/serve-graph.py -- --interactive $*
