#!/bin/bash
set -u -e

# Runs a command inside the Seamless Docker image
# - Current directory is mounted to /cwd, and the command is executed there
# - /tmp is mounted as well
# - Seamless has access to the Docker daemon, so it can launch its own Docker
#    containers via the Docker transformer. This works only under Linux.
#    NOTE: THIS IS A BIG SECURITY HOLE, IT CAN GIVE ROOT ACCESS TO YOUR SYSTEM

# NOTE: it is recommended to run python scripts with 'python -u#

firstarg=$1 #there must be at least one argument

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

docker run --rm \
  $gdbflags \
  --network=host \
  -v `pwd`:/cwd \
  -v /tmp:/tmp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $(getent group docker | cut -d: -f3) \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  rpbs/seamless start.sh $*
