#!/bin/bash

if [ -z "$SEAMLESS_DOCKER_IMAGE" ]; then
  export SEAMLESS_DOCKER_IMAGE=rpbs/seamless
fi

if [ -z "$SEAMLESS_DOCKER_HOST_IP" ]; then

  export SEAMLESS_DOCKER_HOST_IP=$(docker network inspect bridge \
  | python3 -c '''
import json, sys
bridge = json.load(sys.stdin)
print(bridge[0]["IPAM"]["Config"][0]["Gateway"])
''')

fi

if [ -z "$SEAMLESS_DEBUGGING_DIRECTORY" ]; then 
  export SEAMLESS_DEBUGGING_DIRECTORY=/tmp/seamless-debug
  mkdir -p ${SEAMLESS_DEBUGGING_DIRECTORY}
fi

if [ -z "$SEAMLESS_DATABASE_IP" ]; then
  export SEAMLESS_DATABASE_IP=$SEAMLESS_DOCKER_HOST_IP
fi

if [ -z "$SEAMLESS_DATABASE_PORT" ]; then
  export SEAMLESS_DATABASE_PORT=5522
fi

if [ -z "$SEAMLESS_COMMUNION_OUTGOING_IP" ]; then
  export SEAMLESS_COMMUNION_OUTGOING_IP=0.0.0.0
fi

if [ -z "$SEAMLESS_COMMUNION_INCOMING" ]; then
  export SEAMLESS_COMMUNION_INCOMING=""
fi

if [ -z "$SEAMLESS_COMMUNION_IP" ]; then
  export SEAMLESS_COMMUNION_IP=$SEAMLESS_DOCKER_HOST_IP
fi

if [ -z "$SEAMLESS_COMMUNION_PORT" ]; then
  export SEAMLESS_COMMUNION_PORT=5533
fi

if [ -z "$SEAMLESS_COMMUNION_ID" ]; then
  export SEAMLESS_COMMUNION_ID=""
fi

if [ -z "$SEAMLESS_SHARESERVER_ADDRESS" ]; then
  export SEAMLESS_SHARESERVER_ADDRESS=0.0.0.0
fi

if [ -z "$SEAMLESS_DOCKER_RUN_PARAMS_X_NETWORK" ]; then
  export SEAMLESS_DOCKER_RUN_PARAMS_X_NETWORK='--network=bridge'
fi

export SEAMLESS_DOCKER_RUN_PARAMS_X_TRUSTED="""-v /var/run/docker.sock:/var/run/docker.sock \
--group-add $(getent group docker | cut -d: -f3)"""

export SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL='' 
if [ "$SEAMLESS_DOCKER_IMAGE" == seamless-devel ]; then
  if [ -z "$SEAMLESSDIR" ]; then
    echo 'SEAMLESSDIR undefined'
    exit 1
  fi
  export SEAMLESS_DOCKER_RUN_PARAMS_X_DEVEL="-v $SEAMLESSDIR:/seamless -e PYTHONPATH=/seamless"
fi

export SEAMLESS_DOCKER_RUN_PARAMS_X_NAME=''
if [ -n "$SEAMLESS_DOCKER_CONTAINER_NAME" ]; then
    export SEAMLESS_DOCKER_RUN_PARAMS_X_NAME="--name $SEAMLESS_DOCKER_CONTAINER_NAME"
fi

if [ -z ${SEAMLESS_DOCKER_PUBLISH_SHARESERVER_PORTS+x} ]; then
  export SEAMLESS_DOCKER_PUBLISH_SHARESERVER_PORTS="""-p 5813:5813 \
-p 5138:5138"""
fi

if [ -z ${SEAMLESS_DOCKER_PUBLISH_JUPYTER_PORTS+x} ]; then
  export SEAMLESS_DOCKER_PUBLISH_JUPYTER_PORTS="-p 8888:8888"
fi

if [ -z ${SEAMLESS_DOCKER_PUBLISH_DEBUG_PORTS+x} ]; then
  export SEAMLESS_DOCKER_PUBLISH_DEBUG_PORTS="-p 5679:5679"
fi

printenv | sort | python3 -c '''
import sys
for l in sys.stdin.readlines():
  ll = l.split("=")
  if len(ll) == 2 and not len(ll[1].strip()):
    continue
  if ll[0].find("SEAMLESS") > -1: print(l,end="")
'''