#!/bin/bash

# exports the default seamless-minimal conda environment
# (defined in /seamless-minimal/environment.yml)
# to the specified directory
# NOTE: exported directories can be backed up with cp -r
# but when executed, they must run under the original directory name

set -u -e

CONDA_ENV_OUTPUT_DIR=$1
rm -rf $CONDA_ENV_OUTPUT_DIR
mkdir -p $CONDA_ENV_OUTPUT_DIR

docker run \
  --rm \
  -u `id -u`:`id -g` \
  -v $CONDA_ENV_OUTPUT_DIR:/SEAMLESS-CONDA-ENV \
  rpbs/seamless-minimal \
  bash -c 'conda env create --prefix /SEAMLESS-CONDA-ENV --file /seamless-minimal/environment.yml'

docker run \
  --rm \
  -it \
  -u `id -u`:`id -g` \
  -v $CONDA_ENV_OUTPUT_DIR:/SEAMLESS-CONDA-ENV \
  rpbs/seamless-minimal \
  bash -i -c '''
  echo "conda activate /SEAMLESS-CONDA-ENV" >> /.bashrc
  bash -i -c "mamba repoquery search conda -c conda-forge -c main"
  '''  