#!/bin/bash

set -u -e

# Runs an IPython terminal  inside the Seamless Docker image
# - Current directory is mounted to /cwd, and the command is executed there
# - /tmp is mounted as well
# - Seamless has access to the Docker daemon, so it can launch its own Docker
#    containers via the Docker transformer. This works only under Linux.
#    NOTE: THIS IS A BIG SECURITY HOLE, IT CAN GIVE ROOT ACCESS TO YOUR SYSTEM

seamlessdir=$SEAMLESSDIR

###
# The following does not currently work (Ubuntu 18.04.3, Docker 19.03.12); not even --privileged works, unless we are root:
# gdbflags='--cap-add SYS_PTRACE --security-opt=seccomp:unconfined --security-opt=apparmor:unconfined'
gdbflags='' ###

if [[ ! -v SEAMLESS_DEBUGGING_DIRECTORY ]]; then 
  SEAMLESS_DEBUGGING_DIRECTORY=/tmp/seamless-debug
  mkdir -p ${SEAMLESS_DEBUGGING_DIRECTORY}
fi

docker run --rm -it \
  $gdbflags \
  -e DOCKER_IMAGE=rpbs/seamless \
  -v $seamlessdir:/seamless \
  -v ${SEAMLESS_DEBUGGING_DIRECTORY}:${SEAMLESS_DEBUGGING_DIRECTORY} \
  -e "PYTHONPATH=/seamless" \
  -e "SEAMLESS_DEBUGGING_DIRECTORY=${SEAMLESS_DEBUGGING_DIRECTORY}" \
  --network=host \
  -v `pwd`:/cwd \
  -v /tmp:/tmp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --group-add $(getent group docker | cut -d: -f3) \
  --workdir /cwd \
  -u `id -u` \
  --group-add users \
  seamless-devel start.sh ipython3 $*
