#!/bin/bash
set -u -e

[ ! -d ~/.seamless/database ] && mkdir -p ~/.seamless/database
[ ! -d ~/.seamless/redis ] && mkdir -p ~/.seamless/redis

docker run \
  --rm \
  -d \
  -p 6379:6379 \
  --name seamless-redis-container \
  -v ~/.seamless/redis:/data \
  -u `id -u`:`id -g` \
  redis redis-server --appendonly yes --maxmemory 1gb --maxmemory-policy volatile-ttl

docker run \
  --rm \
  -d \
  -p 5522:5522 \
  --name seamless-database-container \
  -v ~/.seamless/database:/data \
  -u jovyan \
  rpbs/seamless \
  python3 -u /home/jovyan/seamless-tools/database.py \
  /home/jovyan/seamless-tools/default-config.yaml
