#!/bin/bash

set -u -e

# loads the specified conda environment into a seamless-minimal
# container and starts a shell
# The conda environment is supposed to have been generated
#  with seamless-conda-env-export, and potentially updated
#  with seamless-conda-env-modify

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`

CONDA_ENV_DIR=$1

HOSTCWD=`pwd`

if [[ ! -v SEAMLESS_DEBUGGING_DIRECTORY ]]; then 
  SEAMLESS_DEBUGGING_DIRECTORY=/tmp/seamless-debug
  mkdir -p ${SEAMLESS_DEBUGGING_DIRECTORY}
fi

HOMEDIR=$(mktemp -d /tmp/temphome-XXXXXXXXXX)
cp $currdir/dummy-bashrc $HOMEDIR/.bashrc
echo 'alias start="conda activate /SEAMLESS-CONDA-ENV"' >> $HOMEDIR/.bashrc
echo 'cd /cwd' >> $HOMEDIR/.bashrc
echo 'echo "To activate the shell, type \"start\""' >> $HOMEDIR/.bashrc

singularity shell \
  --cleanenv \
  --containall \
  --env DOCKER_IMAGE=rpbs/seamless \
  --env "SEAMLESS_DEBUGGING_DIRECTORY=${SEAMLESS_DEBUGGING_DIRECTORY}" \
  --env SEAMLESS_DATABASE_IP=localhost \
  --env SEAMLESS_DATABASE_PORT=5522 \
  --bind $CONDA_ENV_DIR:/SEAMLESS-CONDA-ENV:ro \
  --home $HOMEDIR \
  --env HOSTCWD=$HOSTCWD \
  --shell '/bin/bash' \
  --bind $HOSTCWD:/cwd \
  --bind ${SEAMLESS_DEBUGGING_DIRECTORY}:${SEAMLESS_DEBUGGING_DIRECTORY} \
  $SEAMLESS_MINIMAL_SINGULARITY_IMAGE

rm -rf $HOMEDIR