#!/bin/bash

set -u -e

# modifies a conda environment in the seamless-minimal Docker image
# $1: the environment dir
# $2: the environment.yml file to modify with

currdir=`python3 -c 'import os,sys;print(os.path.dirname(os.path.realpath(sys.argv[1])))' $0`

CONDA_ENV_DIR=$1
yaml=$2

HOMEDIR=$(mktemp -d /tmp/temphome-XXXXXXXXXX)
cp $currdir/dummy-bashrc $HOMEDIR/.bashrc

singularity run \
  --cleanenv \
  --env yaml=$yaml \
  --bind $CONDA_ENV_DIR:/SEAMLESS-CONDA-ENV:rw \
  --home $HOMEDIR \
  $SEAMLESS_MINIMAL_SINGULARITY_IMAGE bash -c -i 'conda activate /SEAMLESS-CONDA-ENV; mamba env update --file $yaml'

rm -rf $HOMEDIR